name: Link check (lychee)
on: { pull_request: {}, push: { branches: ["main"] }, workflow_dispatch: {} }
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: --config lychee.toml --no-progress './**/*.md' './public/**/*.html' './src/**/*.astro'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
